# Generated by Django 3.0.5 on 2020-05-07 10:37

from django.db import migrations
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='geom',
            field=djgeojson.fields.PointField(),
        ),
    ]
