# Generated by Django 3.0.5 on 2020-05-11 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Population',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=50)),
                ('subRegion', models.CharField(max_length=50)),
                ('origin', models.CharField(max_length=50)),
                ('refugeePop', models.IntegerField()),
            ],
        ),
    ]
