# Generated by Django 3.0.5 on 2020-05-04 21:51

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_auto_20200503_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='reference',
            field=models.CharField(default='No Reference Found', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
    ]
